### ISSUE TITLE
Suitable for carla

### ISSUE THREAD

**Issue by Sterley** [zhejz/TrafficBots#3]
Hello, first of all I'd like to congratulate you on your work.
I'd like to try out your method, but I'm using Carla. Do you have a method for converting the Polylines Map you use into an OpenDrive Map, and vice versa?

**Comment by zhejz** [comment]
Hi, thanks for liking our work!
Sorry, but this repo does not support CARLA.

**Comment by Sterley** [comment]
There is no explicit mention of a specific simulator used with the model. The model is not yet integrable with a simulator?

**Comment by zhejz** [comment]
No, it's not.

**Comment by Sterley** [comment]
Thank you for your return !
